package com.project.help.pojo;

import java.util.Date;

public class Data {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data.data_id
     *
     * @mbg.generated Wed May 23 21:40:52 CST 2018
     */
    private Integer dataId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data.student_num
     *
     * @mbg.generated Wed May 23 21:40:52 CST 2018
     */
    private String studentNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data.data_time
     *
     * @mbg.generated Wed May 23 21:40:52 CST 2018
     */
    private Date dataTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data.money
     *
     * @mbg.generated Wed May 23 21:40:52 CST 2018
     */
    private Integer money;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data.place
     *
     * @mbg.generated Wed May 23 21:40:52 CST 2018
     */
    private String place;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data.data_id
     *
     * @return the value of data.data_id
     * @mbg.generated Wed May 23 21:40:52 CST 2018
     */
    public Integer getDataId() {
        return dataId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data.data_id
     *
     * @param dataId the value for data.data_id
     * @mbg.generated Wed May 23 21:40:52 CST 2018
     */
    public void setDataId(Integer dataId) {
        this.dataId = dataId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data.student_num
     *
     * @return the value of data.student_num
     * @mbg.generated Wed May 23 21:40:52 CST 2018
     */
    public String getStudentNum() {
        return studentNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data.student_num
     *
     * @param studentNum the value for data.student_num
     * @mbg.generated Wed May 23 21:40:52 CST 2018
     */
    public void setStudentNum(String studentNum) {
        this.studentNum = studentNum == null ? null : studentNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data.data_time
     *
     * @return the value of data.data_time
     * @mbg.generated Wed May 23 21:40:52 CST 2018
     */
    public Date getDataTime() {
        return dataTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data.data_time
     *
     * @param dataTime the value for data.data_time
     * @mbg.generated Wed May 23 21:40:52 CST 2018
     */
    public void setDataTime(Date dataTime) {
        this.dataTime = dataTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data.money
     *
     * @return the value of data.money
     * @mbg.generated Wed May 23 21:40:52 CST 2018
     */
    public Integer getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data.money
     *
     * @param money the value for data.money
     * @mbg.generated Wed May 23 21:40:52 CST 2018
     */
    public void setMoney(Integer money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data.place
     *
     * @return the value of data.place
     * @mbg.generated Wed May 23 21:40:52 CST 2018
     */
    public String getPlace() {
        return place;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data.place
     *
     * @param place the value for data.place
     * @mbg.generated Wed May 23 21:40:52 CST 2018
     */
    public void setPlace(String place) {
        this.place = place == null ? null : place.trim();
    }
}