package com.project.help.pojo;

public class Student {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.stu_id
     *
     * @mbg.generated Sat May 19 17:16:16 CST 2018
     */
    private Integer stuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.stu_num
     *
     * @mbg.generated Sat May 19 17:16:16 CST 2018
     */
    private String stuNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.stu_name
     *
     * @mbg.generated Sat May 19 17:16:16 CST 2018
     */
    private String stuName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.stu_sex
     *
     * @mbg.generated Sat May 19 17:16:16 CST 2018
     */
    private String stuSex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.stu_age
     *
     * @mbg.generated Sat May 19 17:16:16 CST 2018
     */
    private Integer stuAge;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.stu_major
     *
     * @mbg.generated Sat May 19 17:16:16 CST 2018
     */
    private String stuMajor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.poor_level
     *
     * @mbg.generated Sat May 19 17:16:16 CST 2018
     */
    private String poorLevel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.stu_id
     *
     * @return the value of student.stu_id
     *
     * @mbg.generated Sat May 19 17:16:16 CST 2018
     */
    public Integer getStuId() {
        return stuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.stu_id
     *
     * @param stuId the value for student.stu_id
     *
     * @mbg.generated Sat May 19 17:16:16 CST 2018
     */
    public void setStuId(Integer stuId) {
        this.stuId = stuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.stu_num
     *
     * @return the value of student.stu_num
     *
     * @mbg.generated Sat May 19 17:16:16 CST 2018
     */
    public String getStuNum() {
        return stuNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.stu_num
     *
     * @param stuNum the value for student.stu_num
     *
     * @mbg.generated Sat May 19 17:16:16 CST 2018
     */
    public void setStuNum(String stuNum) {
        this.stuNum = stuNum == null ? null : stuNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.stu_name
     *
     * @return the value of student.stu_name
     *
     * @mbg.generated Sat May 19 17:16:16 CST 2018
     */
    public String getStuName() {
        return stuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.stu_name
     *
     * @param stuName the value for student.stu_name
     *
     * @mbg.generated Sat May 19 17:16:16 CST 2018
     */
    public void setStuName(String stuName) {
        this.stuName = stuName == null ? null : stuName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.stu_sex
     *
     * @return the value of student.stu_sex
     *
     * @mbg.generated Sat May 19 17:16:16 CST 2018
     */
    public String getStuSex() {
        return stuSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.stu_sex
     *
     * @param stuSex the value for student.stu_sex
     *
     * @mbg.generated Sat May 19 17:16:16 CST 2018
     */
    public void setStuSex(String stuSex) {
        this.stuSex = stuSex == null ? null : stuSex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.stu_age
     *
     * @return the value of student.stu_age
     *
     * @mbg.generated Sat May 19 17:16:16 CST 2018
     */
    public Integer getStuAge() {
        return stuAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.stu_age
     *
     * @param stuAge the value for student.stu_age
     *
     * @mbg.generated Sat May 19 17:16:16 CST 2018
     */
    public void setStuAge(Integer stuAge) {
        this.stuAge = stuAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.stu_major
     *
     * @return the value of student.stu_major
     *
     * @mbg.generated Sat May 19 17:16:16 CST 2018
     */
    public String getStuMajor() {
        return stuMajor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.stu_major
     *
     * @param stuMajor the value for student.stu_major
     *
     * @mbg.generated Sat May 19 17:16:16 CST 2018
     */
    public void setStuMajor(String stuMajor) {
        this.stuMajor = stuMajor == null ? null : stuMajor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.poor_level
     *
     * @return the value of student.poor_level
     *
     * @mbg.generated Sat May 19 17:16:16 CST 2018
     */
    public String getPoorLevel() {
        return poorLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.poor_level
     *
     * @param poorLevel the value for student.poor_level
     *
     * @mbg.generated Sat May 19 17:16:16 CST 2018
     */
    public void setPoorLevel(String poorLevel) {
        this.poorLevel = poorLevel == null ? null : poorLevel.trim();
    }
}